version: '3.8'
services:
  stats:
    build: stats-server/stats-service
    image: stats-service-image
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
  stats-db:
    image: postgres:12-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
  main-service:
    build: main-service
    image: main-service-image
    container_name: main-service
    ports:
      - "8080:8080"